project:
  type: book
  output-dir: docs

book:
  title: "BURCU ALTIPARMAK Progress Journal"
  repo-url: https://github.com/BurcuMEF
  chapters:
    - index.qmd
    - report.qmd
format:
  html:
    theme: cosmo


